### ISSUE TITLE
thank you page after submission

### ISSUE THREAD

**Issue by lady3bean** [Bernie-2016/votetracker#11]

**Comment by gnarf** [comment]
not all submissions go directly to thank you, but they should still show a "your form was submitted" that times out after a bit or something.

Caucus reports - only go to "thank you" if it's a "Final Report" otherwise, we want them to still have the information to re-enter if the counts update on the "next count"

Official reports - this form just needs to confirm that data was saved, and then **maybe** empty the fields for the numeric values, but keep county/state selected?

**Comment by gnarf** [comment]
This was already solved in 82bc2a484968e875badc193c652c99c1e65eaac1
